### PR TITLE
Update WCTE macro files

### PR DESCRIPTION
**Pull request by nickwp**
Added three lines that exist in WCSim's macros/WCTE.mac but were missing from the WCTE validation macro files.

### CODE REVIEW

**Comment by nickwp** [comment]
Oh I'm not sure. I assumed the validation script clones the WCSim repository and gets access to all of that, but it seems that other included mac files (e.g. /opt/Validation/Generate/macReference/daq/daq.mac) are in a different location to the standard macros/ directory.

@tdealtry Is there something we can do to get the data/mPMT_Position_WCTE.txt automatically from WCSim? Ideally this should be copied from the WCSim so we don't have to update it manually in this repository every time we update it in the WCSim repository.

**Comment by tdealtry** [comment]
Good question and not something that I've ever thought about...

We've got 2 different scripts that do different things (1 to run WCSim to make the reference files, 1 to run WCSim to make the "current version" files, & produce the comparison plots, webpage etc.). This isn't ideal I know, but was hoping to muddle through this for WCSim before fixing things for GHOST.

Anyway, looking at the current scripts

1. The reference maker [seems to run from `$WCSIM_BUILD_DIR`](https://github.com/WCSim/Validation/blob/master/MakeReference.py#L29). So it should be fine
2. The comparison make is complicated
  - Define a PhysicsValidation test [here](https://github.com/WCSim/Validation/blob/master/tests.txt#L80)
  - Tell it to run each test [here](https://github.com/WCSim/Validation/blob/master/Tests.sh#L263)
  - Which then runs [this script](https://github.com/WCSim/Validation/blob/master/Generate/Generate.sh) to run WCSim & the WCSim file->flat tree script
  - I think this runs from [`/opt/WCSim/install`](https://github.com/WCSim/Validation/blob/master/Tests.sh#L19), which again should be fine

So I'm going to merge this, trigger a WCSim/WCSim comparison CI job & see what happens

**Comment by tdealtry** [comment]
Success on the comparison check. We [see the line](https://github.com/WCSim/WCSim/actions/runs/7728740532/job/21070474217#step:11:276)
```
PMT data file data/mPMT_Position_WCTE.txt is opened to read positions
```
Instead of the fatal alternative from the `if` statement
```
G4cout<<"PMT data file "<<pmtPositionFile<<" could not be opened --> Exiting..."<<G4endl;
exit(-1);
```

**Comment by tdealtry** [comment]
Success in the reference file generator too ([just search for the filename here](https://pipelinesghubeus25.actions.githubusercontent.com/qiQsGPEviRVRlVnlT1fYImxXJo0iIa4bBFANr8ILjZWvDhz9vc/_apis/pipelines/1/runs/441/signedlogcontent/41?urlExpires=2024-01-31T16%3A58%3A11.7892927Z&urlSigningMethod=HMACV1&urlSignature=6KVbNLxo8j46rzOv9CvKuAi%2FEcJB3DLUBQ8CKeT9ARw%3D))

Phew!

**Pull request merged**
